package enumErrCode
	const (
		BUILD_ID_ZHU_FU int = 1//主府
BUILD_ID_XIAOCHANG int = 2//校场
BUILD_ID_MINJU int = 3//民居
BUILD_ID_JIFENGYING int = 4//疾风营
BUILD_ID_TIEBIYING int = 5//铁壁营
BUILD_ID_MUBINGYING int = 6//募兵营
BUILD_ID_CANGKU int = 7//仓库
BUILD_ID_FAMUCHANG int = 8//伐木场
BUILD_ID_LIANTIECHANG int = 9//炼铁场
BUILD_ID_JUNJIYING int = 10//军机营
BUILD_ID_SHANGWUYING int = 11//尚武营
BUILD_ID_MOFANG int = 12//磨坊
BUILD_ID_CAISHICHANG int = 13//采石场
BUILD_ID_DIANJIANGTAIHAN int = 14//点将台汉
BUILD_ID_TONGSHUAITING int = 15//统帅厅
BUILD_ID_CHENGQIANG int = 16//城墙
BUILD_ID_DIANJIANGTAIWEI int = 17//点将台魏
BUILD_ID_DIANJIANGTAISHU int = 18//点将台蜀
BUILD_ID_DIANJIANGTAIWU int = 19//点将台吴
BUILD_ID_JISHI int = 20//集市
BUILD_ID_JINGJIESUO int = 21//警戒所
BUILD_ID_NUQIANG int = 22//女墙
BUILD_ID_DIANJIANGTAIQUN int = 23//点将台群
BUILD_ID_YUBEIYISUO int = 24//预备役所
BUILD_ID_FENGHUOTAI int = 25//烽火台
BUILD_ID_SHOUJIANGFU int = 26//守将府
BUILD_ID_BINGYING int = 27//兵营
BUILD_ID_WUSHENJUXIANG int = 28//武神巨像
BUILD_ID_SHAPANZHENTU int = 29//沙盘阵图
BUILD_ID_FENGCHANTAI int = 30//封禅台
BUILD_ID_SHEJITAN int = 31//社稷坛
BUILD_ID_BEGIN int = 1//建筑id起始 包含
BUILD_ID_END int = 31//建筑id结尾 包含
BUILD_EFF_ID_CITY_BLEED_MAX int = 1//城池耐久度
BUILD_EFF_ID_ARMY_CST int = 2//部队cst
BUILD_EFF_ID_ARMY_CST_CNT int = 3//部队的数量
BUILD_EFF_ID_HERO_ENG_MAX int = 4//武将的活力上限
BUILD_EFF_ID_TAX int = 5//税收
BUILD_EFF_ID_ARMY_SPEED_ADD int = 6//本城部队的加速
BUILD_EFF_ID_ARMY_DEF_ADD int = 7//本城部队的加防
BUILD_EFF_ID_RECRUIT_TIME_DES int = 8//征兵时间减少百分比
BUILD_EFF_ID_RES_MAX int = 9//资源上限
BUILD_EFF_ID_WOOD_PROD int = 10//木资源生产速度
BUILD_EFF_ID_IRON_PROD int = 11//铁资源生产速度
BUILD_EFF_ID_FOOD_PROD int = 12//粮食资源生产速度
BUILD_EFF_ID_STONE_PROD int = 13//石头资源生产速度
BUILD_EFF_ID_ARMY_STRA_ADD int = 14//本城部队的谋略增加
BUILD_EFF_ID_ARMY_ATK_ADD int = 15//本城部队的攻击增加
BUILD_EFF_ID_ARMY_GROUP_HAN int = 16//汉阵营加成千分比
BUILD_EFF_ID_ARMY_GROUP_WEI int = 17//魏阵营加成千分比
BUILD_EFF_ID_ARMY_GROUP_SHU int = 18//蜀阵营加成千分比
BUILD_EFF_ID_ARMY_GROUP_WU int = 19//吴阵营加成千分比
BUILD_EFF_ID_ARMY_GROUP_QUN int = 20//群阵营加成千分比
BUILD_EFF_ID_ARMY_HERO3 int = 21//可配置前锋的部队数
BUILD_EFF_ID_TRADE_ADD int = 22//城市交易比例百分比
BUILD_EFF_ID_DEF_HERO_ARMY int = 23//守城武将兵力_不知道干嘛用的
BUILD_EFF_ID_YUBEI_TIME_DES int = 24//预备兵回复时间减少百分比
BUILD_EFF_ID_YUBEI_MAX int = 25//预备兵上限
BUILD_EFF_ID_DEF_ARMY_CST int = 26//守城部队cst
BUILD_EFF_ID_ALAME int = 27//增加警戒时间
BUILD_EFF_ID_HERO_ARMY_CNT int = 28//武将带兵数
BUILD_EFF_ID_ATK_HURT_DEC int = 29//被攻击时伤害减少百分比_不知道是计算的哪一步
BUILD_EFF_ID_STRA_HURT_DEC int = 30//被谋略时伤害减少百分比_不知道是计算的哪一步
BUILD_EFF_ID_CITY_EXPAND int = 31//城池扩建的块数
BUILD_EFF_ID_FAME_MAX int = 32//名望上限
BUILD_EFF_ID_BEGIN int = 1//建筑效果起始 包含
BUILD_EFF_ID_END int = 32//建筑效果结尾 包含
ITEM_ID_WOOD int = 1001//木材
ITEM_ID_FOOD int = 1002//食物
ITEM_ID_IRON int = 1003//铁矿
ITEM_ID_STONE int = 1004//石材
ITEM_ID_COIN int = 1005//游戏币
ITEM_ID_GOLD int = 1006//RMB
ITEM_ID_FAME int = 1007//名望
LOC_WOOD int = 1001//木材
LOC_FOOD int = 1002//食物
LOC_IRON int = 1003//铁矿
LOC_STONE int = 1004//石材
LOC_COIN int = 1005//游戏币
LOC_GOLD int = 1006//RMB
LOC_HERO_LIST int = 1007//武将列表
LOC_FAME int = 1008//名望
LOC_RES_BEGIN int = 1001//名望
LOC_RES_END int = 1008//名望
LOC_GIFT int = 2001//走cfg_gift
LOC_LOTTERY int = 2002//走cfg_lottery
FIELD_TYPE_EDGE int = 1//边界
FIELD_TYPE_HILL int = 2//山
FIELD_TYPE_RIVAL int = 3//河
FIELD_TYPE_RANDOM int = 4//随机
FIELD_TYPE_STONE int = 5//石场
FIELD_TYPE_FARM int = 6//农场
FIELD_TYPE_WOOD int = 7//森林
FIELD_TYPE_FLAT int = 8//平地
FIELD_TYPE_IRON int = 9//铁山
HERO_ATR_TYPE_YONG int = 1//勇将
HERO_ATR_TYPE_JIANG int = 2//将军
HERO_ATR_TYPE_ZHI int = 3//智将
HERO_ATR_TYPE_CI int = 4//策士
ARMY_COUNT_MAX int = 5//一个玩家拥有的最大军队数量
ARMY_ID_1 int = 1//军队id1
ARMY_ID_2 int = 2//军队id2
ARMY_ID_3 int = 3//军队id3
ARMY_ID_4 int = 4//军队id4
ARMY_ID_5 int = 5//军队id5
SKILL_TYPE_HURT_ATTR int = 1//技能类型  属性绝对值计算
SKILL_TYPE_HURT_DIFF_ATTR int = 2//技能类型  属性相对值计算
SKILL_TYPE_ADD_BLEED int = 3//技能类型 加血，这个一般都是绝对值计算
SKILL_TYPE_BUFFER int = 4//技能类型 设置atr_modify类 buf
SKILL_TYPE_STATUE int = 5//技能类型 设置状态
SKILL_TYPE_EFFTIMES_STATUE int = 6//技能类型  次数状态
SKILL_TYPE_CLEAR_GOOD_BUFFER int = 7//技能类型 清空好buff
SKILL_TYPE_CLEAR_BAD_BUFFER int = 8//技能类型 清空坏buff
SKILL_TYPE_CLEAR_GOOD_STATUE int = 9//技能类型 清空好状态
SKILL_TYPE_CLEAR_BAD_STATUE int = 10//技能类型 清空坏状态
SKILL_TYPE_ATTACK int = 11//技能类型  普通攻击
SKILL_TYPE_ARROW_NTK int = 12//技能类型  飞羽攻击
SKILL_TYPE_OPPO_HURT_ATTR int = 13//技能类型  根据对方的属性绝对值计算
STATUE_UNABLE_ATK int = 2//状态不能攻击
STATUE_UNABLE_BE_ATK int = 3//状态不能被攻击
STATUE_UNABLE_SKILL int = 4//状态不能放被动技能
STATUE_UNABLE_BE_TEAMER_SKILL int = 5//状态不能被队友放技能
STATUE_UNABLE_BE_ENEMY_SKILL int = 6//状态不能被敌人放技能
STATUE_UNABLE_BE_SKILL int = 7//状态不能被放技能
STATUE_UNABLE_MAN_SKILL int = 8//状态不能放主动技能
STATUE_UNABLE_BE_MAN_SKILL int = 9//状态不能被主动技能释放
STATUE_UNABLE_BE_TEAMER_BUFFER int = 10//状态不能被队友放BUFF
STATUE_UNABLE_BE_ENEMY_BUFFER int = 11//状态不能被敌人放BUFF
STATUE_UNABLE_BE_BUFFER int = 12//状态不能被放BUFF
STATUE_UNABLE_BE_TEAMER_STATUE int = 13//状态不能被队友放状态
STATUE_UNABLE_BE_ENEMY_STATUE int = 14//状态不能被敌人放状态
STATUE_UNABLE_BE_STATUE int = 15//状态不能被放状态
STATUE_UNABLE_DEAD int = 16//免死状态
STATUE_UNABLE_BE_ARROW_ATK int = 17//免飞羽状态
STATUE_UNABLE_ARROW_ATK int = 18//不能释放飞羽
TAR_IDX_SELF int = 1//目标位置
TAR_IDX_TEAMER_PLATFORM int = 2//目标位置
TAR_IDX_TEAMER_BEFORE_SELF int = 3//目标位置
TAR_IDX_TEAMER_AFTER_SELF int = 4//目标位置
TAR_IDX_TEAMER_ALL int = 5//目标位置
TAR_IDX_OPPO_THE_SAME_POS int = 6//目标位置
TAR_IDX_OPPO_PLATFORM int = 7//目标位置
TAR_IDX_OPPO_BEFORE_SELF int = 8//目标位置
TAR_IDX_OPPO_AFTER_SELF int = 9//目标位置
TAR_IDX_OPPO_ALL int = 10//目标位置
ATR_SPEED int = 1//属性idx
ATR_WULI int = 2//属性idx
ATR_ZHILI int = 3//属性idx
ATR_TONGSHAI int = 4//属性idx
ATR_MAX int = 5//属性Max
CALC_ATR_BLEED int = 5//血量
CALC_ATR_MAX_BLEED int = 6//血量最大值
CALC_ATR_WU_ATK int = 7//物攻
CALC_ATR_WU_DEF int = 8//物防
CALC_ATR_ZHI_ATK int = 9//智攻
CALC_ATR_ZHI_DEF int = 10//智防
CALC_ATR_ARROW_ATK int = 11//箭伤害
CALC_ATR_SPEED int = 12//速度
CALC_ATR_APPEND_ATK int = 13//追击
CALC_ATR_AUTO_ADD_BLEED int = 14//自动回血
ALL_ATR_MAX int = 15//属性Max
BUF_TY_GOOD_BUFFER int32 = 1//好的buff
BUF_TY_BAD_BUFFER int32 = 2//坏的buff
HERO_RECRUIT_TYPE_COIN_1_TIMES int32 = 1//用银币抽卡1次
HERO_RECRUIT_TYPE_COIN_10_TIMES int32 = 2//用银币抽卡10次
HERO_RECRUIT_TYPE_DIAMOND_1_TIMES int32 = 3//用金币抽卡1次
HERO_RECRUIT_TYPE_DIAMOND_10_TIMES int32 = 4//用金币抽卡10次
HERO_RECRUIT_SPEC_TIMES int32 = 10//逢10会有特殊抽奖
HERO_RECRUIT_TENTH_POOL_ID int32 = 3//逢10会有特殊抽奖
HERO_RECRUIT_SPEC_STAR int32 = 5//抽到5星卡会有次数累计的变化
CALC_ATR_ARROW int32 = 1//测试
	)