namespace game.data.autogen
{
	static class EnumConst{
		public static int BUILD_ID_ZHU_FU= 1;//主府
		public static int BUILD_ID_XIAOCHANG= 2;//校场
		public static int BUILD_ID_MINJU= 3;//民居
		public static int BUILD_ID_JIFENGYING= 4;//疾风营
		public static int BUILD_ID_TIEBIYING= 5;//铁壁营
		public static int BUILD_ID_MUBINGYING= 6;//募兵营
		public static int BUILD_ID_CANGKU= 7;//仓库
		public static int BUILD_ID_FAMUCHANG= 8;//伐木场
		public static int BUILD_ID_LIANTIECHANG= 9;//炼铁场
		public static int BUILD_ID_JUNJIYING= 10;//军机营
		public static int BUILD_ID_SHANGWUYING= 11;//尚武营
		public static int BUILD_ID_MOFANG= 12;//磨坊
		public static int BUILD_ID_CAISHICHANG= 13;//采石场
		public static int BUILD_ID_DIANJIANGTAIHAN= 14;//点将台汉
		public static int BUILD_ID_TONGSHUAITING= 15;//统帅厅
		public static int BUILD_ID_CHENGQIANG= 16;//城墙
		public static int BUILD_ID_DIANJIANGTAIWEI= 17;//点将台魏
		public static int BUILD_ID_DIANJIANGTAISHU= 18;//点将台蜀
		public static int BUILD_ID_DIANJIANGTAIWU= 19;//点将台吴
		public static int BUILD_ID_JISHI= 20;//集市
		public static int BUILD_ID_JINGJIESUO= 21;//警戒所
		public static int BUILD_ID_NUQIANG= 22;//女墙
		public static int BUILD_ID_DIANJIANGTAIQUN= 23;//点将台群
		public static int BUILD_ID_YUBEIYISUO= 24;//预备役所
		public static int BUILD_ID_FENGHUOTAI= 25;//烽火台
		public static int BUILD_ID_SHOUJIANGFU= 26;//守将府
		public static int BUILD_ID_BINGYING= 27;//兵营
		public static int BUILD_ID_WUSHENJUXIANG= 28;//武神巨像
		public static int BUILD_ID_SHAPANZHENTU= 29;//沙盘阵图
		public static int BUILD_ID_FENGCHANTAI= 30;//封禅台
		public static int BUILD_ID_SHEJITAN= 31;//社稷坛
		public static int BUILD_ID_BEGIN= 1;//建筑id起始 包含
		public static int BUILD_ID_END= 31;//建筑id结尾 包含
		public static int BUILD_EFF_ID_CITY_BLEED_MAX= 1;//城池耐久度
		public static int BUILD_EFF_ID_ARMY_CST= 2;//部队cst
		public static int BUILD_EFF_ID_ARMY_CNT= 3;//部队的数量
		public static int BUILD_EFF_ID_HERO_ENG_MAX= 4;//武将的活力上限
		public static int BUILD_EFF_ID_TAX= 5;//税收
		public static int BUILD_EFF_ID_ARMY_SPEED_ADD= 6;//本城部队的加速
		public static int BUILD_EFF_ID_ARMY_DEF_ADD= 7;//本城部队的加防
		public static int BUILD_EFF_ID_RECRUIT_TIME_DES= 8;//征兵时间减少百分比
		public static int BUILD_EFF_ID_RES_MAX= 9;//资源上限
		public static int BUILD_EFF_ID_WOOD_PROD= 10;//木资源生产速度
		public static int BUILD_EFF_ID_IRON_PROD= 11;//铁资源生产速度
		public static int BUILD_EFF_ID_FOOD_PROD= 12;//粮食资源生产速度
		public static int BUILD_EFF_ID_STONE_PROD= 13;//石头资源生产速度
		public static int BUILD_EFF_ID_ARMY_STRA_ADD= 14;//本城部队的谋略增加
		public static int BUILD_EFF_ID_ARMY_ATK_ADD= 15;//本城部队的攻击增加
		public static int BUILD_EFF_ID_ARMY_GROUP_HAN= 16;//汉阵营加成千分比
		public static int BUILD_EFF_ID_ARMY_GROUP_WEI= 17;//魏阵营加成千分比
		public static int BUILD_EFF_ID_ARMY_GROUP_SHU= 18;//蜀阵营加成千分比
		public static int BUILD_EFF_ID_ARMY_GROUP_WU= 19;//吴阵营加成千分比
		public static int BUILD_EFF_ID_ARMY_GROUP_QUN= 20;//群阵营加成千分比
		public static int BUILD_EFF_ID_ARMY_HERO3= 21;//可配置前锋的部队数
		public static int BUILD_EFF_ID_TRADE_ADD= 22;//城市交易比例百分比
		public static int BUILD_EFF_ID_DEF_HERO_ARMY= 23;//守城武将兵力_不知道干嘛用的
		public static int BUILD_EFF_ID_YUBEI_TIME_DES= 24;//预备兵回复时间减少百分比
		public static int BUILD_EFF_ID_YUBEI_MAX= 25;//预备兵上限
		public static int BUILD_EFF_ID_DEF_ARMY_CST= 26;//守城部队cst
		public static int BUILD_EFF_ID_ALAME= 27;//增加警戒时间
		public static int BUILD_EFF_ID_HERO_ARMY_CNT= 28;//武将带兵数
		public static int BUILD_EFF_ID_ATK_HURT_DEC= 29;//被攻击时伤害减少百分比_不知道是计算的哪一步
		public static int BUILD_EFF_ID_STRA_HURT_DEC= 30;//被谋略时伤害减少百分比_不知道是计算的哪一步
		public static int BUILD_EFF_ID_CITY_EXPAND= 31;//城池扩建的块数
		public static int BUILD_EFF_ID_FAME_MAX= 32;//名望上限
		public static int BUILD_EFF_ID_BEGIN= 1;//建筑效果起始 包含
		public static int BUILD_EFF_ID_END= 32;//建筑效果结尾 包含
		public static int ITEM_ID_WOOD= 1001;//木材
		public static int ITEM_ID_FOOD= 1002;//食物
		public static int ITEM_ID_IRON= 1003;//铁矿
		public static int ITEM_ID_STONE= 1004;//石材
		public static int ITEM_ID_COIN= 1005;//游戏币
		public static int ITEM_ID_GOLD= 1006;//RMB
		public static int ITEM_ID_FAME= 1007;//名望
		public static int LOC_WOOD= 1001;//木材
		public static int LOC_FOOD= 1002;//食物
		public static int LOC_IRON= 1003;//铁矿
		public static int LOC_STONE= 1004;//石材
		public static int LOC_COIN= 1005;//游戏币
		public static int LOC_GOLD= 1006;//RMB
		public static int LOC_HERO_LIST= 2003;//英雄列表
		public static int LOC_FAME= 1008;//名望
		public static int LOC_RES_BEGIN= 1001;//名望
		public static int LOC_RES_END= 1008;//名望
		public static int LOC_GIFT= 2001;//走cfg_gift
		public static int LOC_LOTTERY= 2002;//走cfg_lottery
		public static int LOC_HERO_LIST= 2003;//英雄列表
		public static int FIELD_TYPE_EDGE= 1;//边界
		public static int FIELD_TYPE_HILL= 2;//山
		public static int FIELD_TYPE_RIVAL= 3;//河
		public static int FIELD_TYPE_RANDOM= 4;//随机
		public static int FIELD_TYPE_STONE= 5;//石场
		public static int FIELD_TYPE_FARM= 6;//农场
		public static int FIELD_TYPE_WOOD= 7;//森林
		public static int FIELD_TYPE_FLAT= 8;//平地
		public static int FIELD_TYPE_IRON= 9;//铁山
		public static int HERO_ATR_TYPE_YONG= 1;//勇将
		public static int HERO_ATR_TYPE_JIANG= 2;//将军
		public static int HERO_ATR_TYPE_ZHI= 3;//智将
		public static int HERO_ATR_TYPE_CI= 4;//策士
		public static int ARMY_COUNT_MAX= 5;//一个玩家拥有的最大军队数量
		public static int ARMY_ID_1= 1;//军队id1
		public static int ARMY_ID_2= 2;//军队id2
		public static int ARMY_ID_3= 3;//军队id3
		public static int ARMY_ID_4= 4;//军队id4
		public static int ARMY_ID_5= 5;//军队id5
		public static int SKILL_TYPE_HURT_ATTR= 1;//技能类型  属性绝对值计算
		public static int SKILL_TYPE_HURT_DIFF_ATTR= 2;//技能类型  属性相对值计算
		public static int SKILL_TYPE_ADD_BLEED= 3;//技能类型 加血，这个一般都是绝对值计算
		public static int SKILL_TYPE_BUFFER= 4;//技能类型 设置atr_modify类 buf
		public static int SKILL_TYPE_STATUE= 5;//技能类型 设置状态
		public static int SKILL_TYPE_EFFTIMES_STATUE= 6;//技能类型  次数状态
		public static int SKILL_TYPE_CLEAR_GOOD_BUFFER= 7;//技能类型 清空好buff
		public static int SKILL_TYPE_CLEAR_BAD_BUFFER= 8;//技能类型 清空坏buff
		public static int SKILL_TYPE_CLEAR_GOOD_STATUE= 9;//技能类型 清空好状态
		public static int SKILL_TYPE_CLEAR_BAD_STATUE= 10;//技能类型 清空坏状态
		public static int SKILL_TYPE_ATTACK= 11;//技能类型  普通攻击
		public static int SKILL_TYPE_ARROW_NTK= 12;//技能类型  飞羽攻击
		public static int SKILL_TYPE_OPPO_HURT_ATTR= 13;//技能类型  根据对方的属性绝对值计算
		public static int STATUE_UNABLE_ATK= 2;//状态不能攻击
		public static int STATUE_UNABLE_BE_ATK= 3;//状态不能被攻击
		public static int STATUE_UNABLE_SKILL= 4;//状态不能放被动技能
		public static int STATUE_UNABLE_BE_TEAMER_SKILL= 5;//状态不能被队友放技能
		public static int STATUE_UNABLE_BE_ENEMY_SKILL= 6;//状态不能被敌人放技能
		public static int STATUE_UNABLE_BE_SKILL= 7;//状态不能被放技能
		public static int STATUE_UNABLE_MAN_SKILL= 8;//状态不能放主动技能
		public static int STATUE_UNABLE_BE_MAN_SKILL= 9;//状态不能被主动技能释放
		public static int STATUE_UNABLE_BE_TEAMER_BUFFER= 10;//状态不能被队友放BUFF
		public static int STATUE_UNABLE_BE_ENEMY_BUFFER= 11;//状态不能被敌人放BUFF
		public static int STATUE_UNABLE_BE_BUFFER= 12;//状态不能被放BUFF
		public static int STATUE_UNABLE_BE_TEAMER_STATUE= 13;//状态不能被队友放状态
		public static int STATUE_UNABLE_BE_ENEMY_STATUE= 14;//状态不能被敌人放状态
		public static int STATUE_UNABLE_BE_STATUE= 15;//状态不能被放状态
		public static int STATUE_UNABLE_DEAD= 16;//免死状态
		public static int STATUE_UNABLE_BE_ARROW_ATK= 17;//免飞羽状态
		public static int STATUE_UNABLE_ARROW_ATK= 18;//不能释放飞羽
		public static int TAR_IDX_SELF= 1;//目标位置
		public static int TAR_IDX_TEAMER_PLATFORM= 2;//目标位置
		public static int TAR_IDX_TEAMER_BEFORE_SELF= 3;//目标位置
		public static int TAR_IDX_TEAMER_AFTER_SELF= 4;//目标位置
		public static int TAR_IDX_TEAMER_ALL= 5;//目标位置
		public static int TAR_IDX_OPPO_THE_SAME_POS= 6;//目标位置
		public static int TAR_IDX_OPPO_PLATFORM= 7;//目标位置
		public static int TAR_IDX_OPPO_BEFORE_SELF= 8;//目标位置
		public static int TAR_IDX_OPPO_AFTER_SELF= 9;//目标位置
		public static int TAR_IDX_OPPO_ALL= 10;//目标位置
		public static int ATR_SPEED= 1;//属性idx
		public static int ATR_WULI= 2;//属性idx
		public static int ATR_ZHILI= 3;//属性idx
		public static int ATR_TONGSHAI= 4;//属性idx
		public static int ATR_MAX= 5;//属性Max
		public static int CALC_ATR_BLEED= 5;//血量
		public static int CALC_ATR_MAX_BLEED= 6;//血量最大值
		public static int CALC_ATR_WU_ATK= 7;//物攻
		public static int CALC_ATR_WU_DEF= 8;//物防
		public static int CALC_ATR_ZHI_ATK= 9;//智攻
		public static int CALC_ATR_ZHI_DEF= 10;//智防
		public static int CALC_ATR_ARROW_ATK= 11;//箭伤害
		public static int CALC_ATR_SPEED= 12;//速度
		public static int CALC_ATR_APPEND_ATK= 13;//追击
		public static int CALC_ATR_AUTO_ADD_BLEED= 14;//自动回血
		public static int ALL_ATR_MAX= 15;//属性Max
		public static int BUF_TY_GOOD_BUFFER= 1;//好的buff
		public static int BUF_TY_BAD_BUFFER= 2;//坏的buff
		public static int HERO_RECRUIT_TYPE_COIN_1_TIMES= 1;//用银币抽卡1次
		public static int HERO_RECRUIT_TYPE_COIN_10_TIMES= 2;//用银币抽卡10次
		public static int HERO_RECRUIT_TYPE_DIAMOND_1_TIMES= 3;//用金币抽卡1次
		public static int HERO_RECRUIT_TYPE_DIAMOND_10_TIMES= 4;//用金币抽卡10次
		public static int HERO_RECRUIT_SPEC_TIMES= 10;//逢10会有特殊抽奖
		public static int HERO_RECRUIT_TENTH_POOL_ID= 3;//逢10会有特殊抽奖
		public static int HERO_RECRUIT_SPEC_STAR= 5;//抽到5星卡会有次数累计的变化
}