namespace game.data.autogen
{
	static class EnumConst{
		public static int BUILD_ID_ZHU_FU= 1;//主府
		public static int BUILD_ID_XIAOCHANG= 2;//校场
		public static int BUILD_ID_MINJU= 3;//民居
		public static int BUILD_ID_JIFENGYING= 4;//疾风营
		public static int BUILD_ID_TIEBIYING= 5;//铁壁营
		public static int BUILD_ID_MUBINGYING= 6;//募兵营
		public static int BUILD_ID_CANGKU= 7;//仓库
		public static int BUILD_ID_FAMUCHANG= 8;//伐木场
		public static int BUILD_ID_LIANTIECHANG= 9;//炼铁场
		public static int BUILD_ID_JUNJIYING= 10;//军机营
		public static int BUILD_ID_SHANGWUYING= 11;//尚武营
		public static int BUILD_ID_MOFANG= 12;//磨坊
		public static int BUILD_ID_CAISHICHANG= 13;//采石场
		public static int BUILD_ID_DIANJIANGTAIHAN= 14;//点将台汉
		public static int BUILD_ID_TONGSHUAITING= 15;//统帅厅
		public static int BUILD_ID_CHENGQIANG= 16;//城墙
		public static int BUILD_ID_DIANJIANGTAIWEI= 17;//点将台魏
		public static int BUILD_ID_DIANJIANGTAISHU= 18;//点将台蜀
		public static int BUILD_ID_DIANJIANGTAIWU= 19;//点将台吴
		public static int BUILD_ID_JISHI= 20;//集市
		public static int BUILD_ID_JINGJIESUO= 21;//警戒所
		public static int BUILD_ID_NUQIANG= 22;//女墙
		public static int BUILD_ID_DIANJIANGTAIQUN= 23;//点将台群
		public static int BUILD_ID_YUBEIYISUO= 24;//预备役所
		public static int BUILD_ID_FENGHUOTAI= 25;//烽火台
		public static int BUILD_ID_SHOUJIANGFU= 26;//守将府
		public static int BUILD_ID_BINGYING= 27;//兵营
		public static int BUILD_ID_WUSHENJUXIANG= 28;//武神巨像
		public static int BUILD_ID_SHAPANZHENTU= 29;//沙盘阵图
		public static int BUILD_ID_FENGCHANTAI= 30;//封禅台
		public static int BUILD_ID_SHEJITAN= 31;//社稷坛
		public static int BUILD_ID_BEGIN= 1;//建筑id起始 包含
		public static int BUILD_ID_END= 31;//建筑id结尾 包含
		public static int BUILD_EFF_ID_CITY_BLEED_MAX= 1;//城池耐久度
		public static int BUILD_EFF_ID_ARMY_CST= 2;//部队cst
		public static int BUILD_EFF_ID_ARMY_CNT= 3;//部队的数量
		public static int BUILD_EFF_ID_HERO_ENG_MAX= 4;//武将的活力上限
		public static int BUILD_EFF_ID_TAX= 5;//税收
		public static int BUILD_EFF_ID_ARMY_SPEED_ADD= 6;//本城部队的加速
		public static int BUILD_EFF_ID_ARMY_DEF_ADD= 7;//本城部队的加防
		public static int BUILD_EFF_ID_RECRUIT_TIME_DES= 8;//征兵时间减少百分比
		public static int BUILD_EFF_ID_RES_MAX= 9;//资源上限
		public static int BUILD_EFF_ID_WOOD_PROD= 10;//木资源生产速度
		public static int BUILD_EFF_ID_IRON_PROD= 11;//铁资源生产速度
		public static int BUILD_EFF_ID_FOOD_PROD= 12;//粮食资源生产速度
		public static int BUILD_EFF_ID_STONE_PROD= 13;//石头资源生产速度
		public static int BUILD_EFF_ID_ARMY_STRA_ADD= 14;//本城部队的谋略增加
		public static int BUILD_EFF_ID_ARMY_ATK_ADD= 15;//本城部队的攻击增加
		public static int BUILD_EFF_ID_ARMY_GROUP_HAN= 16;//汉阵营加成千分比
		public static int BUILD_EFF_ID_ARMY_GROUP_WEI= 17;//魏阵营加成千分比
		public static int BUILD_EFF_ID_ARMY_GROUP_SHU= 18;//蜀阵营加成千分比
		public static int BUILD_EFF_ID_ARMY_GROUP_WU= 19;//吴阵营加成千分比
		public static int BUILD_EFF_ID_ARMY_GROUP_QUN= 20;//群阵营加成千分比
		public static int BUILD_EFF_ID_ARMY_HERO3= 21;//可配置前锋的部队数
		public static int BUILD_EFF_ID_TRADE_ADD= 22;//城市交易比例百分比
		public static int BUILD_EFF_ID_DEF_HERO_ARMY= 23;//守城武将兵力_不知道干嘛用的
		public static int BUILD_EFF_ID_YUBEI_TIME_DES= 24;//预备兵回复时间减少百分比
		public static int BUILD_EFF_ID_YUBEI_MAX= 25;//预备兵上限
		public static int BUILD_EFF_ID_DEF_ARMY_CST= 26;//守城部队cst
		public static int BUILD_EFF_ID_ALAME= 27;//增加警戒时间
		public static int BUILD_EFF_ID_HERO_ARMY_CNT= 28;//武将带兵数
		public static int BUILD_EFF_ID_ATK_HURT_DEC= 29;//被攻击时伤害减少百分比_不知道是计算的哪一步
		public static int BUILD_EFF_ID_STRA_HURT_DEC= 30;//被谋略时伤害减少百分比_不知道是计算的哪一步
		public static int BUILD_EFF_ID_CITY_EXPAND= 31;//城池扩建的块数
		public static int BUILD_EFF_ID_FAME_MAX= 32;//名望上限
		public static int BUILD_EFF_ID_BEGIN= 1;//建筑效果起始 包含
		public static int BUILD_EFF_ID_END= 32;//建筑效果结尾 包含
		public static int ITEM_ID_WOOD= 1001;//木材
		public static int ITEM_ID_FOOD= 1002;//食物
		public static int ITEM_ID_IRON= 1003;//铁矿
		public static int ITEM_ID_STONE= 1004;//石材
		public static int ITEM_ID_COIN= 1005;//游戏币
		public static int ITEM_ID_GOLD= 1006;//RMB
		public static int ITEM_ID_FAME= 1007;//名望
}